### ISSUE TITLE
fails with latest bigchaindb version 

### ISSUE THREAD

**Issue by realgt** [bigchaindb/bigchaindb-react-redux-boilerplate#3]
This project fails with v2 of bigchaindb. When running `docker compose ps`, bigchaindb command status is Exit Code 1.
Logs below:
```
$ make
docker-compose build mdb
mdb uses an image, skipping
docker-compose build bdb
bdb uses an image, skipping
docker-compose build client
Building client
Step 1/7 : FROM node:8.9
 ---> 672002a50a0b
Step 2/7 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> 2f1672f3a74e
Step 3/7 : WORKDIR /usr/src/app
 ---> Using cache
 ---> dfede99735fc
Step 4/7 : COPY . /usr/src/app
 ---> 84559b9d45ef
Step 5/7 : RUN npm install -g yarn
 ---> Running in af16eb928eb8
/usr/local/bin/yarn -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/bin/yarnpkg -> /usr/local/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.9.4
added 1 package in 1.07s
Removing intermediate container af16eb928eb8
 ---> 269afb4e0bd1
Step 6/7 : RUN rm -rf node_modules
 ---> Running in e91926cfe407
Removing intermediate container e91926cfe407
 ---> 0f83507d8648
Step 7/7 : RUN yarn
 ---> Running in 82c2ccb55d31
yarn install v1.9.4
info No lockfile found.
[1/4] Resolving packages...
warning react-scripts > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-scripts > babel-preset-react-app > babel-preset-env > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-scripts > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-scripts > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-scripts > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-scripts > jest > jest-cli > istanbul-api > istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 42.17s.
Removing intermediate container 82c2ccb55d31
 ---> bc6f83e98b7f
Successfully built bc6f83e98b7f
Successfully tagged testchain_client:latest
docker-compose stop mdb
docker-compose rm -f mdb
Going to remove testchain_mdb_1
Removing testchain_mdb_1 ... done
docker-compose up -d mdb
Creating testchain_mdb_1 ... done
sleep 10
docker-compose up -d bdb
Starting testchain_bdb_1 ... done
docker-compose up -d client
Recreating testchain_client_1 ... done
```

```
$ docker-compose ps
       Name                     Command               State             Ports          
---------------------------------------------------------------------------------------
testchain_bdb_1      bigchaindb start                 Exit 1                           
testchain_client_1   npm start                        Up       0.0.0.0:3000->3000/tcp  
testchain_mdb_1      docker-entrypoint.sh mongo ...   Up       0.0.0.0:32768->27017/tcp

```
Here is the output of `$ docker-compose logs -t -f bdb`
```bdb_1     | 2018-08-16T01:13:38.381846711Z INFO:bigchaindb.config_utils:Cannot find config file '/data/.bigchaindb'.
bdb_1     | 2018-08-16T01:13:38.523417804Z [2018-08-16 01:13:38] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 2.0.0b5 (MainProcess - pid: 1)
bdb_1     | 2018-08-16T01:13:38.618673017Z [2018-08-16 01:13:38] [WARNING] (bigchaindb.backend.localmongodb.connection) Lost connection to the database, retrying query. (MainProcess - pid: 1)
bdb_1     | 2018-08-16T01:13:39.099568289Z Traceback (most recent call last):
bdb_1     | 2018-08-16T01:13:39.099596637Z   File "/usr/local/lib/python3.6/site-packages/bigchaindb/backend/localmongodb/connection.py", line 61, in run
bdb_1     | 2018-08-16T01:13:39.100348129Z     return query.run(self.conn)
bdb_1     | 2018-08-16T01:13:39.100359979Z   File "/usr/local/lib/python3.6/site-packages/bigchaindb/utils.py", line 166, in run
bdb_1     | 2018-08-16T01:13:39.100656990Z     last = last(*item[0], **item[1])
bdb_1     | 2018-08-16T01:13:39.100668601Z   File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 1262, in find_one
bdb_1     | 2018-08-16T01:13:39.101576151Z     for result in cursor.limit(-1):
bdb_1     | 2018-08-16T01:13:39.101586910Z   File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1189, in next
bdb_1     | 2018-08-16T01:13:39.102441372Z     if len(self.__data) or self._refresh():
bdb_1     | 2018-08-16T01:13:39.102453687Z   File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1104, in _refresh
bdb_1     | 2018-08-16T01:13:39.102790195Z     self.__send_message(q)
bdb_1     | 2018-08-16T01:13:39.102814907Z   File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 982, in __send_message
bdb_1     | 2018-08-16T01:13:39.103109745Z     helpers._check_command_response(first)
bdb_1     | 2018-08-16T01:13:39.103118136Z   File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 132, in _check_command_response
bdb_1     | 2018-08-16T01:13:39.103439086Z     raise NotMasterError(errmsg, response)
bdb_1     | 2018-08-16T01:13:39.103450154Z pymongo.errors.NotMasterError: node is not in primary or recovering state
bdb_1     | 2018-08-16T01:13:39.103456518Z 
bdb_1     | 2018-08-16T01:13:39.103471035Z During handling of the above exception, another exception occurred:
bdb_1     | 2018-08-16T01:13:39.103476360Z 
bdb_1     | 2018-08-16T01:13:39.103481320Z Traceback (most recent call last):
bdb_1     | 2018-08-16T01:13:39.103486488Z   File "/usr/local/lib/python3.6/site-packages/bigchaindb/backend/localmongodb/connection.py", line 65, in run
bdb_1     | 2018-08-16T01:13:39.103576117Z     return query.run(self.conn)
bdb_1     | 2018-08-16T01:13:39.103587541Z   File "/usr/local/lib/python3.6/site-packages/bigchaindb/utils.py", line 166, in run
bdb_1     | 2018-08-16T01:13:39.103694512Z     last = last(*item[0], **item[1])
bdb_1     | 2018-08-16T01:13:39.103705367Z   File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 1262, in find_one
bdb_1     | 2018-08-16T01:13:39.104078989Z     for result in cursor.limit(-1):
bdb_1     | 2018-08-16T01:13:39.104105346Z   File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1189, in next
bdb_1     | 2018-08-16T01:13:39.104454575Z     if len(self.__data) or self._refresh():
bdb_1     | 2018-08-16T01:13:39.104465031Z   File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1104, in _refresh
bdb_1     | 2018-08-16T01:13:39.104765652Z     self.__send_message(q)
bdb_1     | 2018-08-16T01:13:39.104770484Z   File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 982, in __send_message
bdb_1     | 2018-08-16T01:13:39.105325080Z     helpers._check_command_response(first)
bdb_1     | 2018-08-16T01:13:39.105335699Z   File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 132, in _check_command_response
bdb_1     | 2018-08-16T01:13:39.105435731Z     raise NotMasterError(errmsg, response)
bdb_1     | 2018-08-16T01:13:39.105445007Z pymongo.errors.NotMasterError: node is not in primary or recovering state
bdb_1     | 2018-08-16T01:13:39.105448059Z 
bdb_1     | 2018-08-16T01:13:39.105450566Z The above exception was the direct cause of the following exception:
bdb_1     | 2018-08-16T01:13:39.105453172Z 
bdb_1     | 2018-08-16T01:13:39.105455516Z Traceback (most recent call last):
bdb_1     | 2018-08-16T01:13:39.105457920Z   File "/usr/local/bin/bigchaindb", line 11, in <module>
bdb_1     | 2018-08-16T01:13:39.105508173Z     load_entry_point('BigchainDB==2.0.0b5', 'console_scripts', 'bigchaindb')()
bdb_1     | 2018-08-16T01:13:39.105517709Z   File "/usr/local/lib/python3.6/site-packages/bigchaindb/commands/bigchaindb.py", line 247, in main
bdb_1     | 2018-08-16T01:13:39.105949606Z     utils.start(create_parser(), sys.argv[1:], globals())
bdb_1     | 2018-08-16T01:13:39.105962829Z   File "/usr/local/lib/python3.6/site-packages/bigchaindb/commands/utils.py", line 133, in start
bdb_1     | 2018-08-16T01:13:39.106313220Z     return func(args)
bdb_1     | 2018-08-16T01:13:39.106321844Z   File "/usr/local/lib/python3.6/site-packages/bigchaindb/commands/utils.py", line 44, in configure
bdb_1     | 2018-08-16T01:13:39.106415756Z     command(args)
bdb_1     | 2018-08-16T01:13:39.106423289Z   File "/usr/local/lib/python3.6/site-packages/bigchaindb/commands/bigchaindb.py", line 173, in run_start
bdb_1     | 2018-08-16T01:13:39.106541339Z     run_recover(bigchaindb.lib.BigchainDB())
bdb_1     | 2018-08-16T01:13:39.106556775Z   File "/usr/local/lib/python3.6/site-packages/bigchaindb/commands/bigchaindb.py", line 153, in run_recover
bdb_1     | 2018-08-16T01:13:39.106627551Z     pre_commit = query.get_pre_commit_state(b.connection, PRE_COMMIT_ID)
bdb_1     | 2018-08-16T01:13:39.106634084Z   File "/usr/local/lib/python3.6/functools.py", line 803, in wrapper
bdb_1     | 2018-08-16T01:13:39.107426481Z     return dispatch(args[0].__class__)(*args, **kw)
bdb_1     | 2018-08-16T01:13:39.107446027Z   File "/usr/local/lib/python3.6/site-packages/bigchaindb/backend/localmongodb/query.py", line 278, in get_pre_commit_state
bdb_1     | 2018-08-16T01:13:39.107890671Z     projection={'_id': False}))
bdb_1     | 2018-08-16T01:13:39.107911089Z   File "/usr/local/lib/python3.6/site-packages/bigchaindb/backend/localmongodb/connection.py", line 67, in run
bdb_1     | 2018-08-16T01:13:39.107991928Z     raise ConnectionError from exc
bdb_1     | 2018-08-16T01:13:39.107999710Z bigchaindb.backend.exceptions.ConnectionError
testchain_bdb_1 exited with code 1```

**Comment by vasa-develop** [comment]
@manolodewiner @realgt Any updates on this?
